ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS experience_name VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phase_2_answer_1 TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phase_2_answer_2 TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phase_2_answer_3 TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phase_2_answer_4 TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phase_2_answer_5 TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phase_2_answer_6 TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS establishment_name VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS experience_type VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS country VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reservation_method VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS monthly_reservations INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS payment_method VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS has_instagram VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS uses_instagram_for_sales VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS main_pain_point TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_qualified BOOLEAN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS disqualification_reason VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS conversation_state VARCHAR NOT NULL DEFAULT 'PHASE_1';
ALTER TABLE users ADD COLUMN IF NOT EXISTS language VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS follow_up_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_follow_up_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS demos (
    id SERIAL PRIMARY KEY,
    user_phone VARCHAR NOT NULL UNIQUE REFERENCES users(phone) ON DELETE CASCADE,
    title VARCHAR NOT NULL,
    duration_minutes INTEGER NOT NULL,
    description TEXT NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    google_calendar_event_id VARCHAR,
    upcoming_reminder_sent_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);